### ISSUE TITLE
Error with evilgrade at start

### ISSUE THREAD

**Issue by PestiB9** [infobyte/evilgrade#5]
When i start evilgrade i have this error:
Use of uninitialized value $prompt in concatenation (.) or string at /usr/lib/x86_64-linux-gnu/perl5/5.20/Term/ReadLine/Gnu.pm line 308.
I reinstalled the package of perl but i continue to get it and i can't utilize any command

**Comment by f-amato** [comment]
Hi @PestiB9, could you please send us more information about your SO ? 
Best

**Comment by PestiB9** [comment]
Yeah sorry, i'm using linux kali 2.0; i installed evilgrade 2 days ago and also the Data::Dump with apt-get install libdata-dump-perl. First time it seem that i could use it, no errors. Yestarday after the reboot it show this message

**Comment by f-amato** [comment]
Hi @PestiB9 it's seems like a problem in new version of ReadLine::Gnu. I can reproduce it in Kali 2.0. I'll try to fix it and let you know.

**Comment by learn3r** [comment]
@f-amato I also get the same error while run evilgrade on kali 2.0 .. any fix ??? or fix soon bro

**Comment by ortholinux** [comment]
I have used this tool in old backtrack days and was working fine, now using first time in kali and having the same problem the guys mentioned above.

**Comment by thedp** [comment]
Kali 2.0 same error.

**Comment by homayoun16** [comment]
I am not sure if anyone is still having problems with this but I have found a workaround which can be temporarily applied to fixed the issue. the culprit seems to be a perl module called libterm-readline-gnu-perl so to temporarily fix it use this command to remove the module:
apt-get remove libterm-readline-gnu-perl then after doing your pen testing install the module by this command: apt-get install libterm-readline-gnu-perl

**Comment by macwhiz** [comment]
Likewise, same problem on evilgrade 2.0.7 with Kali Rolling 2016.1.

**Comment by mattaereal** [comment]
Fixed. Please update your evilgrade version to current.

For the curious: 
Latest version of ReadLine::Gnu seems to have an issue on line 308. It does not contemplate that the $prompt variable could be empty. It could be easily fixed with an unless but that's not part of evilgrade.

So the current fix was to catch inside Shell.pm the case where ReadLine was getting used in a similar scenario.

**Comment by joeisgood99** [comment]
Im still getting this issue (or a very similar one) on Kali rolling 2016.1. with fresh git clone as of 25/06/2016.
Have installed  RPC::XML and  Data::Dump with apt-get install librpc-xml-perl && apt-get install libdata-dump-perl.

Error:
 www.infobytesec.com 
- 78 modules available.

evilgrade>Use of uninitialized value $prompt in concatenation (.) or string at /usr/lib/x86_64-linux-gnu/perl5/5.22/Term/ReadLine/Gnu.pm line 318
